apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: event-driven-face-existence-detection
  name: event-driven-face-existence-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      run: event-driven-face-existence-detection
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: event-driven-face-existence-detection
    spec:
      hostname: event-driven-face-existence-detection
      containers:
        - name: event-driven-face-existence-detection
          image: latonaio/event-driven-face-existence-detection
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8888"
            - name: OBSERVATION_DIR
              value: "/var/lib/aion/Data/analyze"
            - name: OBSERVATION_FILE
              value: "standbyImageForFaceDetection.jpg"
            - name: DETECT_INTERVAL
              value: "5"
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/aion/Data
            - name: ui
              mountPath: /var/lib/aion/FaceDetection/event-driven-face-existence-detection/public/
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
      volumes:
      - name: data
        hostPath:
          path: /var/lib/aion/default/Data
      - name: ui
        hostPath:
          path: /var/lib/aion/FaceDetection/event-driven-face-existence-detection/public/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: event-driven-face-existence-detection
  name: event-driven-face-existence-detection
spec:
  selector:
    run: event-driven-face-existence-detection
  type: ClusterIP
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
